name = "eaglercraft-sync-worker"
main = "index.js"
compatibility_date = "2024-12-05"

compatibility_flags = [ "nodejs_compat" ]

[vars]
GITHUB_OWNER = "CkWebGamingStudios"
GITHUB_REPO = "Eaglercraft-"
