name = "eaglercraft-sync-worker"
main = "index.js"
compatibility_date = "2024-12-05"

# Optional: turn off Node.js compatibility
node_compat = false

[vars]
GITHUB_OWNER = "CkWebGamingStudios"
GITHUB_REPO = "Eaglercraft-"

# Secrets added via Cloudflare dashboard or wrangler secret
